"""changing orders table

Revision ID: 40fc5236ae07
Revises: bd9bb9b61727
Create Date: 2026-10-06 04:44:10.557076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fc5236ae07'
down_revision: Union[str, Sequence[str], None] = 'bd9bb9b61727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('unit_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'unit_price')
    # ### end Alembic commands ###
